BBPATH =. "${LAYERDIR}:"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "aislim"
BBFILE_PATTERN_aislim = "^${LAYERDIR}/"
BBFILE_PRIORITY_aislim = "60"

LAYERVERSION_aislim = "1"
LAYERDEPENDS_aislim = "core tegra tegrademo"
LAYERSERIES_COMPAT_aislim = "blacksail"
