BBPATH =. "${LAYERDIR}:"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "embedai"
BBFILE_PATTERN_embedai = "^${LAYERDIR}/"
BBFILE_PRIORITY_embedai = "60"

LAYERVERSION_embedai = "1"
LAYERDEPENDS_embedai = "core tegra tegrademo"
LAYERSERIES_COMPAT_embedai = "blacksail"
